const Maps = [
    `
XXXXXXXXXXXXXXXXXX
S          sXXXXXX
XXXXXXXXXXO XXXXXX
XXXXXXXXXXO OXXXXX
Xe               E
X OXXXXXXXO OXXXXX
Xn         wXXXXXX
XXXXXXXXXXXXXXXXXX
`,
    `
XXXXOOSSOOXXXXXXXX
XXXXOO  OOXXXXXXXX
XXXXOO  OOOOOOOOOO
XXXXOO  OOOOOOOOOO
XXXXOO e         E
XXXXOOe          E
XXXXOOOOOOOOOOOOOO
XXXXOOOOOOOOOOOOOO`,

    `
XXXXXXXXXXXXXXXXXXXX
S                 sX
SsOOOOOOOOOOOOOOOO X
Xe               s X
XXXXXXXXXXXXXXXXO  X
XXXXXXXXXXXXXXXXO eE
XXXXXXXXXXXXXXXXOe E
XXXXXXXXXXXXXXXXXXXX`
];
