/*
X = obstacle where nothing can be placed
O = obstacle where towers can be placed
S = start
E = end
n = ship will turn north
s = ship will turn south
w = ship will turn west
e = ship will turn east
*/

const Maps = [
  // map for testing basic stuff
    `
OOOOOOOOOOOO
OOOOOOOOOOOO
S          E
OOOOOOOOOOOO
OOOOOOOOOOOO
S          E
OOOOOOOOOOOO
OOOOOOOOOOOO`,
/*
         1         2
12345678901234567890
*/
    `
OOSSOOOOOOOOOOOOEEOO
OO  Oe  sOOe    n OO
OO  O OO OO OOOOO OO
OO  O OO OO OOOOO OO
OO  O OOe  nOOOOO OO
OO  O OOOOOOOOOOO OO
OO  O OOOOOOOOOOO OO
OO  O OOOOOOOe   nOO
OO  O OOOOOOO OOOOOO
OO  O OOOOe  nOOOOOO
OO  O OOOO OOOOOOOOO
OO  O e   nOOOOOOOOO
OO  O  OOOOOOOOOOOOO
OO  O  OOOOOOOOOOOOO
OO  O  OOOOOOOOOOOOO
OO  O  OOOOOOOOOOOOO
OO e n OOOOOOOOOOOOO
OOe   nOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOO
    `,
    `
OOOOOOOOOOOOOOOOOO
S         sOOOOOOO
OOOOOOOOOO OOOOOOO
OOOOOOOOOO OOOOOOO
Oe               E
O OOOOOOOO OOOOOOO
On        wOOOOOOO
OOOOOOOOOOOOOOOOOO
`,
    `
OOOOOOSSOOOOOOOOOO
OOOOOO  OOOOOOOOOO
OOOOOO  OOOOOOOOOO
OOOOOO  OOOOOOOOOO
OOOOOO e         E
OOOOOOe          E
OOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOO`,

    `
OOOOOOOOOOOOOOOOOOOO
S                 sO
SsOOOOOOOOOOOOOOOO O
Oe               s O
OOOOOOOOOOOOOOOOO  O
OOOOOOOOOOOOOOOOO eE
OOOOOOOOOOOOOOOOOe E
OOOOOOOOOOOOOOOOOOOO`
];
