/*
X = obstacle where nothing can be placed
O = obstacle where towers can be placed
S = start
E = end
n = ship will turn north
s = ship will turn south
w = ship will turn west
e = ship will turn east
*/

const Maps = [
  // map for testing basic stuff
  /*
    `
OOOOOOOOOOOO
OOOOOOOOOOOO
S          E
OOOOOOOOOOOO
OOOOOOOOOOOO
S          E
OOOOOOOOOOOO
OOOOOOOOOOOO`,
*/
/*
         1         2
12345678901234567890
*/
  /*
    `
OSOOOOOOOOOOOOOOOOO
O OOOOOOOOOOOOOOOOO
O OOOOOOOOOOOOOOOOO
Oe     sOOOOOOOOOOO
OOOOOOO OOOOOOOOOOO
OOOOOOO OOOOOOOOOOO
OOOOOOO OOOOOOOOOOO
OOOOOOO OOOOOOOOOOO
OOOOOOOe          E
OOOOOOOOOOOOOOOOOOO
OOOOOOOe          E
OOOOOOO OOOOOOOOOOO
OOOOOOO OOOOOOOOOOO
OOOOOOO OOOOOOOOOOO
OOOOOOO OOOOOOOOOOO
Oe     nOOOOOOOOOOO
O OOOOOOOOOOOOOOOOO
O OOOOOOOOOOOOOOOOO
OSOOOOOOOOOOOOOOOOO
    `,
*/
    `
OOOOOOOOOOOOOOOOOO
S         sOOOOOOO
OOOOOOOOOO OOOOOOO
OOOOOOOOOO OOOOOOO
Oe               E
O OOOOOOOO OOOOOOO
On        wOOOOOOO
OOOOOOOOOOOOOOOOOO
`,
/*
         1         2
12345678901234567890
*/
    `
OOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOO
OOs          wOOOO
OO OOOOOOOOOO OOOO
OO OOOOOOOOOO OOOO
OO OOOOOOOOe     E
OO OOOOOOOO O OOOO
OOe        nO OOOO
OOOOOOOOOOOOO OOOO
OOOOOOOOOOOOO OOOO
S            nOOOO
OOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOO`,

    `
OOOOOOOOOOOOOOOOOOOO
OOOOOOOOOe         E
OOOOOOOOO OOOOOOOOOO
S          sOOOOOOOO
OOOOOOOOO O OOOOOOOO
S        nO OOOOOOOO
OOOOOOOOOOO OOOOOOOO
OOOOOOOOOOOe       E
OOOOOOOOOOOOOOOOOOOO`
];
